name: Optimize map and deploy

on: [ push ]

permissions:
  contents: write
  pages: write
  actions: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.4
        name: Install pnpm
        with:
          version: 7
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'

      - name: "Install dependencies"
        run: pnpm install

      - name: "Build scripts"
        run: pnpm build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        if: github.ref == 'refs/heads/main'
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: dist/ # The folder the action should deploy.
          BASE_BRANCH: main

      - name: Bash2
        run: |
          ls -al
